---
language: ruby
before_install: gem install bundler -v 1.11.2
cache:    bundler
script:   bundle  exec rspec
rvm:
  - '2.2'
  - ruby-head
  - rbx-2.4.1
  - rbx-head
  - jruby-9.0.0.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head
